name: "NPM Release @stripe/sdk-migrator"

on:
  workflow_dispatch: {}

jobs:
  sdk-migrator-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Install Oathtool  
        run: sudo apt-get install -y oathtool
      - name: Publish to NPM
        run: |
          set +ex
          npm config set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
          npm publish --otp="$(oathtool -b --totp $NPM_OTP)" --ignore-scripts --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_OTP: ${{ secrets.NPM_OTP }}
